### ISSUE TITLE
Add EvolutionRTS Chobby download links

### ISSUE THREAD

**Issue by gajop** [EvolutionRTS/Evolution-RTS#111]
Linux: https://spring-launcher.ams3.digitaloceanspaces.com/EvolutionRTS/Evolution-RTS/Evolution%20RTS.AppImage

Windows: https://spring-launcher.ams3.digitaloceanspaces.com/EvolutionRTS/Evolution-RTS/Evolution%20RTS.exe

**Comment by silentwings** [comment]
Will Evo become free of WebLobby with this?

Asking due to timing for https://springrts.com/phpbb/viewtopic.php?f=64&t=37758, which when it comes will render legacy lobby clients unable to create new user accounts.

**Comment by Damgam** [comment]
As soon as it will be fully usable, yes.
:)

**Comment by silentwings** [comment]
Great, some estimate of how long it takes would be helpful!

**Comment by ForbodingAngel** [comment]
Well currently we can join a game but can't download the map nor add it manually. I'm not sure that Damgam nor myself are the correct people to ask. We will test it as things get fixed, but atm as far as I know, Gajop is the only person who is fixing these issues.

**Comment by gajop** [comment]
I've reported that issue upstream to pr-downloader and waiting for them to resolve them

**Comment by silentwings** [comment]
upstream report: https://github.com/spring/pr-downloader/issues/112

**Comment by silentwings** [comment]
What is preventing this from happening? 

Afaik pr-dl is now fully functional. If Chobby bugfixes are needed I can offer them (they should be reported).

**Comment by ForbodingAngel** [comment]
Frustratingly, time. The only person I can test with is @Damgam . It doesn't help that the wrapper is dumping everything into appdata, but that's a Gajop thing, not a chobby complaint.

I will try my hardest to give it a thorough test tomorrow after I get home from work.

**Comment by gajop** [comment]
What issue is AppData causing?
What would be a better path and would I be able to automatically detect/compute this for all Windows users?

**Comment by ForbodingAngel** [comment]
Programs should never be installed to appdata. I understand that's because fucking Google does it now everyone thinks they can do it, but it's a wack move.

Windows has environment variables for this:
%PROGRAMFILES% and %PROGRAMFILESx86%

If you want the directory to be writeable by all users, then use icacls to make the directory writeable by all.

ICACLS "%cd%" /grant Everyone:F /T

I answered this back in 2011 when ppl we're wrestling with UAC in win7

https://springrts.com/phpbb/viewtopic.php?t=26325

But a better method for the install folder would be to ask the user, and automatically suggest a location in program files, like every other sane installer. Then, pull a steam and immediately use icacls on that install folder.

If you want to get cute, you can even use set and setx to add an environment variable to the system pointing at your install folder. Set is temp and setx is perm.

This isn't new info and it isn't hard to do either.

**Comment by gajop** [comment]
Modifying the directory to be writable by all users after install isn't where I'm struggling though.
I'm using electron-builder to distribute and self-update the launcher.
For Windows this relies on NSIS, which describes the possible settings here: https://www.electron.build/configuration/nsis
I'm using this configuration: https://github.com/gajop/spring-launcher/blob/master/package.json#L33-L36

Right now install **and** self-update work smoothly which I don't want to ruin.
Last time I played with these settings for Windows it produced builds that would force users to go through the long wizard each time they'd update, which would give awful UX.
I don't really have strong feelings about the location, but if you want to change its default location or provide different behavior (by allowing path to be specified), then you need to test it on Windows.
It's effectively just cloning it, installing npm and running `npm install` and `npm run build-win`! So I extend this invitation to tinker any Windows dev interested!

**Comment by ForbodingAngel** [comment]
Clicking most buttons ends up with a black screen. Spring fails to load repeatedly. The installer creates a springsettings that triggers the bug where the spring process never shows on screen even though it is still running and must be killed via task manager. Only way to fix it is to delete spring settings.

Clicking login causes nothing to happen except the login button disappears. Clicking on any other button after that causes black screen.

I uploaded the log but here:
http://logs.springrts.com/logfiles/58/

Tried it multiple times clicking different things with no real different results. Second button click seems to always cause black screen. Clicking any button has no observable resulting action.

These are essentially the exact same bugs that I reported a few months ago in discord.

**Comment by silentwings** [comment]
> The installer creates a springsettings that triggers the bug where the spring process never shows on screen even though it is still running and must be killed via task manager.

This sounds like https://github.com/Spring-Chobby/Chobby/issues/460, is already on my radar.

> These are essentially the exact same bugs that I reported a few months ago in discord.

If you report them to the chobby bugtracker, I might have (i) known they existed and (ii) tried to fix them!

**Comment by Damgam** [comment]
I have the same problem as Forb.
Clicking anything = black screen.
Same error as you mentioned above.

**Comment by ForbodingAngel** [comment]
Are the reports here sufficient @silentwings ?

**Comment by silentwings** [comment]
I think so, linked to https://github.com/Spring-Chobby/Chobby/issues/467. I'm travelling atm, but will look into it.

**Comment by gajop** [comment]
Should work now. Delete LuaMenu and springsettings.cfg before trying again.
I also took the liberty to disable various ZK settings, which you probably don't need.

PS: The issue was in evorts gameConfig, which you are expected to maintain. 
You can use the spring-launcher to run the lobby in dev mode (select it in the top right after starting it). Either copy or link Chobby.sdd to the relevant games directory, e.g. in my case: `/home/gajop/.config/Evolution RTS/games/Chobby.sdd`

**Comment by ForbodingAngel** [comment]
Trying to log in results in "Invalid Sentence format, please update your lobby client.

https://i.imgur.com/lJLQclp.jpg

I don't even know where the gameconfig is. I have no idea what "running the dev lobby" would help me with. At the moment I just want to get to a point of basic functionality.

**Comment by ForbodingAngel** [comment]
Bug Reports:
Initially it starts in full screen. Closing and reopening it results in a window. Clicking on a button on the second run results in a black screen and stuck process.

Subsequent runs after that result in the age old bug where the spring process starts but displays nothing, always is fixed by deleting spring settings.

So I delete springsettings and chobby starts. 2 Button clicks and black screen. I can make it function *once* by deleting luamenu and springsettings, but it goes right back to the previous behavior.

I tried uploading the log. Maybe it will have something useful.
http://logs.springrts.com/logfiles/60/

**Comment by gajop** [comment]
The game config is located at https://github.com/Spring-Chobby/Chobby/tree/master/LuaMenu/configs/gameConfig/evorts . You should be aware of it as you created it originally - the bug was there which is why I alluded that you could fix it by using the dev version of Chobby.

PS: it's important to delete both springsettings AND LuaMenu as I instructed earlier.

**Comment by ForbodingAngel** [comment]
> PS: it's important to delete both springsettings AND LuaMenu as I instructed earlier.

You didn't properly understand what I wrote (Perhaps you didn't see the separate "Bug Reports" comment?). Of course I deleted springsettings and luamenu before even trying to run the launcher today.

Yes, I created it 3 years ago in preparation for chobby integrating with uberserver. For straightforward reasons it makes sense that I wouldn't remember where it was.

Thanks :-)

**Comment by gajop** [comment]
Huh, you wrote it indeed, my bad, missed it.

If you could upload the infolog when the black screen happens, that'd be great. The new log was empty.
May need to do it manually.. or maximize the launcher from the tray

**Comment by silentwings** [comment]
seems no bug reports related to this?

**Comment by ForbodingAngel** [comment]
Well the most recent issue has been pr downloader

**Comment by ForbodingAngel** [comment]
https://github.com/spring/pr-downloader/issues/112#issuecomment-464677959

**Comment by silentwings** [comment]
that issue is closed

**Comment by ForbodingAngel** [comment]
With no clear resolution.

**Comment by silentwings** [comment]
rubbish, the ticket was fixed, and regarding your last post on it you were asked "please open a new ticket as its mostly unrelated to this one."

where is that ticket?

**Comment by ForbodingAngel** [comment]
> maintenance should have same pr-downloader as develop

This tells me nothing. Was anything changed?

**Comment by silentwings** [comment]
unless tickets exist (esp when invited to create one), after some time period it will be assumed that they are not required -> nothing is blocking

**Comment by ForbodingAngel** [comment]
Generally, if you know that an issue exists and no one makes an issue of it, the issue doesn't magically disappear.

**Comment by silentwings** [comment]
i don't currently know of an issue that exists, you should make a ticket if there is one.

**Comment by ForbodingAngel** [comment]
Also, not for nothing, if it worked, we would be using it. If we aren't, it's because something isn't working.

**Comment by silentwings** [comment]
"something isn't working"

so make a ticket to say what ....

**Comment by ForbodingAngel** [comment]
It's not like the info wasn't there, new ticket or not. Bugs don't fix themselves/ Regardless I copy pasted into a new issue (as anyone could have done if they really cared). Still broken.

**Comment by gajop** [comment]
The repo is moved to https://github.com/EvolutionRTS/EvoRTS-Chobby . Closing this PR.
