### ISSUE TITLE
Reverse state toggle widget throws an error

### ISSUE THREAD

**Issue by ForbodingAngel** [EvolutionRTS/Evolution-RTS#119]
[f=0000104] [widgets_evo.lua] Error: Error in CommandNotify(): [string "LuaUI/Widgets_Evo/cmd_state_reverse_toggle...."]:20: bad argument #1 to 'spGetCmdDescIndex' (number expected, got nil)

I think BAR uses this, so maybe just copy pasta

**Comment by Ruwetuin** [comment]
bar widget is identical

**Comment by ForbodingAngel** [comment]
Ruh Roh

Looks like it is probably just an arguments change in the engine. I'll have a look a bit later.

**Comment by ForbodingAngel** [comment]
Dunno what caused this error before, but it works fine now.
