### ISSUE TITLE
game keeps crashing

### ISSUE THREAD

**Issue by shivachirr** [EvolutionRTS/Evolution-RTS#12]
so every time i try to play the game in sp mode to learn how to play i keep getting an access exception error. i looked at the log and i think it has to do my graphics drive but not sure. the link below will contain the log.

-> https://drive.google.com/file/d/0B4ZNJDO5qt8IWVlTLUpCdmlvR1U/view?usp=sharing

**Comment by db81** [comment]
Yeah it's one of those notorious ATI crashes. Sometimes upgrading drivers does help, but it's not guaranteed.

**Comment by shivachirr** [comment]
yeah i just upgraded to the latest beta driver at most the map loads but
when it trys to appear it still crashes

**Comment by db81** [comment]
Try ticking safe mode in settings.

**Comment by shivachirr** [comment]
nope still crash on an acess exception

**Comment by db81** [comment]
Welp, there's nothing we can do. ATI just doesn't play along with Spring.

You can disable the game filter (bottom right in Battles tab) and see if other games work (they use a newer version of the engine) but I doubt they will.

**Comment by shivachirr** [comment]
ok
