### ISSUE TITLE
Singleplayer v8.99 broken - Can't finish building buildings

### ISSUE THREAD

**Issue by frameworld** [EvolutionRTS/Evolution-RTS#14]
The building disappears after it's 5-25% finished
The % is a bit random, but depends on required build time.

**Comment by ForbodingAngel** [comment]
It will stop building and pop the nanoframe instantly (and give you a refund) if you tell the builder to go do something else while it is building. Use Shift to queue orders :-)

**Comment by frameworld** [comment]
I didn't gave another order. I was playing single vs bot (not on multiplayer-hosts)

I started the game and gave just 1 order. it works if I play multiplayer and fails any time I start a single-player.

**Comment by ForbodingAngel** [comment]
Can you please give me the infolog after one of these games has been completed? (Settings >pastebin infolog >give me the link).

Thanks :-)

**Comment by ForbodingAngel** [comment]
Actually what I really need is the demo file. Start a game, replicate this, then go to 
program files/steam/steam apps/common/evolution rts/evo_data/demos/*.sdf
(It will be the one that was created within the last few minutes)

**Comment by frameworld** [comment]
https://dl-web.dropbox.com/get/Spring/infolog.txt?_subject_uid=456494996&w=AAAtYuUL3TwSDbmBUKTrXhAKSo4_8MzY-jpNlngbPPK76A
https://dl-web.dropbox.com/get/Spring/20150914_084324_wanderlust_V01_100.sdf?_subject_uid=456494996&w=AAAHc-zNSU8NSbxAJZc7WYX6llsPFs9r7goB59J7xpko-Q

**Comment by ForbodingAngel** [comment]
http://i.imgur.com/sI3D6R4.png

Dude, when you click "pastebin infolog" it gives you a link, why not just give me that link?

Thanks, just need to make them so I can see them.

**Comment by frameworld** [comment]
Sorry. it should be visible now.
I haven't used dropbox much jet and does pastebin allow to download demo files?

For the case it doesn't work, I've used pastebin at least for the infolog: http://paste.springfiles.com/view/32490808#L6

**Comment by ForbodingAngel** [comment]
Use spring 96. Evo isn't compatible with 100 yet.
