### ISSUE TITLE
Spring issues

### ISSUE THREAD

**Issue by TheRedLord143** [EvolutionRTS/Evolution-RTS#16]
Always crashes no matter what

**Comment by ForbodingAngel** [comment]
At what point does it crash? Do you get an error message? Please open my documents > my games > spring > infolog.txt and copy and paste it's contents into pastebin.com and give me the pastebin link it gives you. Sorry you're having trouble.

**Comment by ForbodingAngel** [comment]
Closing due to age and lack of info.
