### ISSUE TITLE
Evolution wont start.

### ISSUE THREAD

**Issue by brianbowhan** [EvolutionRTS/Evolution-RTS#17]
Im running openSUSE 42.1, Steam client, and Evolution exits with: " istFilesPriv(): not a directory: "/home/bbowhan/.local/share/Steam/steamapps/common/EvolutionRTS/lib/evo_data/engine"  "

**Comment by ForbodingAngel** [comment]
Ok, it has been noted. The lobby changed the engine folder. I thought he had set an exception for evo but apparently not. I will update the builds as soon as I have a chance. I'm sorry for the trouble.

**Comment by db81** [comment]
This error shouldn't cause it to exit though, so that's not right if it does.

Sorry about the folder change mess.

**Comment by ForbodingAngel** [comment]
Fixed a long time ago.
