### ISSUE TITLE
The Game crashes at starting point

### ISSUE THREAD

**Issue by siwex** [EvolutionRTS/Evolution-RTS#18]
I've got problem at lunching the game. I have chosen the map, i have chosen the game (Evolution RTS v8.99) add some bots and tried to start. when i launch the game, the screen is black for short period of time, and then the error is showed up with message "Archive `spring features v1.6` not found".
what should i do?
P.S. it's all about the custom skirmish

**Comment by ForbodingAngel** [comment]
This is a result of a bad build I pushed yesterday. I'm fixing it now. Sorry for the trouble.

**Comment by ForbodingAngel** [comment]
I've pushed out a fix for this while I update the steam builds. Just join any multiplayer lobby that has version 9.01 and everything will be automatically downloaded for you.

**Comment by siwex** [comment]
Ok, thanks, i had this problem after launching any configuration with maps from "my maps", with others, there's no problem.

**Comment by ForbodingAngel** [comment]
Great :-D
