### ISSUE TITLE
Keep getting an acces violation when i try to start a sp game

### ISSUE THREAD

**Issue by MrLovelyName** [EvolutionRTS/Evolution-RTS#21]
when I get everything set up and play the game everything is normal but then the screen kicks out and says

 Spring has crashed: Access violation
A stacktrace has been written to: C:\Program Files(x86)\Steam\steamapps\common\EvolutionRTS\evo_data\infolog.txt 

what do I do to fix this please?

**Comment by db81** [comment]
Go to settings and click "pastebin infolog.txt" and give us the link. It's most likely a problem with ATI drivers. Also try enabling safe mode in settings and see if that helps.

**Comment by MrLovelyName** [comment]
well trying it in safe mode didn't work so here is the infolog.txt link  http://paste.springfiles.com/view/0db8f363

**Comment by db81** [comment]
```
[f=0000000] Error: This stack trace indicates a problem with your graphic card driver.
Please try upgrading or downgrading it. Specifically recommended is the latest driver,
and one that is as old as your graphic card. Make sure to use a driver removal utility,
before installing other drivers.
```
Yeah an AMD driver crash. Spring doesn't play well with those. There's work underway to switch to a newer version on the engine which supposedly works better with AMD.

**Comment by ForbodingAngel** [comment]
What are your computer specs?

Also infolog on line 584 says:

[f=0000000] Error: Stacktrace for Spring 96.0:

[f=0000000] Error: This stack trace indicates a problem with your graphic
card driver. Please try upgrading or downgrading it. Specifically
recommended is the latest driver, and one that is as old as your graphic
card. Make sure to use a driver removal utility, before installing other
drivers.


102 is ALMOST a go. I implemented a shader framework by one of the engine
devs that is proving to be amazing and fucking difficult at the same time.
When it stops crashing the gadget handler every time a unit dies, we should
be well on the way for a release.

**Comment by MrLovelyName** [comment]
well I'm tight on money right now so I guess I cant play your game but when I do get a better one ill be sure to give it a go

**Comment by ForbodingAngel** [comment]
New version should be out relatively soon, which may increase compatibility for bad drivers.
