### ISSUE TITLE
Get hbots ingame and finalize how they will function

### ISSUE THREAD

**Issue by ForbodingAngel** [EvolutionRTS/Evolution-RTS#39]
5 hbots have been created and their models are ready to be imported. The Peewee is already ingame.

- [ ] Engineer
- [x] Peewee
- [x] Pyro
- [x] Rocko
- [x] Thud
- [ ] Factory

**Comment by ForbodingAngel** [comment]
So I had the great idea of making all of the h-Bot weapons penetrating weapons. That should be interesting.

**Comment by RSAStudioGames** [comment]
Sounds awesome!
