### ISSUE TITLE
can't build buildings

### ISSUE THREAD

**Issue by shibumi** [EvolutionRTS/Evolution-RTS#41]
I have really no idea what I do wrong. But everytime when I try to build a building the building process is stopped after 1 second. I have tried different spring versions:

springlobby version: 0.249
spring versions: 96, 100, 102, 103
Evolution RTS version: 9.06

**Comment by ForbodingAngel** [comment]
In the current release version, if you stop building something, it cancels it immediately. My guess is that you are telling the unit to build something, and then giving it another order at which point the unit tries to follow the subsequent order immediately, which interrupts the build process.

Easy fix, press and hold shift while giving multiple orders and they will be queued up :-)

**Comment by shibumi** [comment]
@ForbodingAngel 
Ok. No I have the reason. I wasn't playing with engine 96. i was playing with Engine 103. Seems like 103 and evolution are incompatible.

But I have some other bug with the spam bot on level easy. After round about 8 minutes the queen is spawning. This is damn too early. How can I change this?

**Comment by ForbodingAngel** [comment]
Ohhh, yeah that would do it. Actually I recommend that you join the Evolution RTS alpha test server. It is using engine version 103 and it's much better. It's still in testing, but it's quite stable. It includes an AI called "ShardLua" that works really well.

http://evolutionrts.info/208/development-updates-massive-strides-forward-lots-goodies/
