### ISSUE TITLE
Error Downloading game Evolution RTS - v9.06

### ISSUE THREAD

**Issue by TheFaber** [EvolutionRTS/Evolution-RTS#46]
So I don't know if I'm supposed to post this here but I couldn't find anywhere else to post it. SO I installed this game knowing that it didn't install the game directly but the spring web host wont install the game it only pops up saying this when I join a lobby

Error Downloading game Evolution RTS - v9.06:
No game found for Evolution RTS - v9.06

Any help would be nice

**Comment by ForbodingAngel** [comment]
Oh here is fine :-) The important part that you didn't add here is that you were using the skirmish thing. That makes it a different issue. I'mma copy pasta my answer on the forums here :-)

> Best thing to do would be to click on the multiplayer tab and use the servers there. I recommend playing the alpha, because imo it's a FAR better game than the current released steam version. It's a bit rough around the edges, but it's a lot more fun.

To play with a bot, ONLY use a shardlua bot. Not Shard, Shardlua. They are different :-)
