### ISSUE TITLE
Shortening the Siege Phase

### ISSUE THREAD

**Issue by Trensicourt** [EvolutionRTS/Evolution-RTS#48]
I find that defense within the game is too strong for their cost.

I believe a good Real Time Strategy should focus it's attention on the battles between armies, not the siege at your enemy's base. If the skirmish phase is longer than the siege phase, then it's either an imbalance of player skills or of some flaw with game design. In the case, the issue appears to be the latter, a flaw in game design, since siege phases are longer than skirmish phases.

Why is this bad?
Having longer sieges means boring gameplay. The winning player should not produce several armies nor produce anti-building weapons to win a siege. A castle without an army should fall easy to an overwhelming army. That means, if a player loses on the battlefield, then he/she should lose even faster when hiding in base with an even smaller army. However, this is not the case. The defending player just has to make more defense while the aggressive player has to either switch to artillery or nukes, both of which are expensive and time-consuming. That's because smashing a 200/200 army of MBTs into a base doesn't work.

My fixes:
Number 1: Replace all towers types with Balanced, Artillery, Anti-Air, Faction-Based
Balanced Towers deal low damage, but has high health. It's meant to delay armies for a fraction of a second before being wiped out. It's best served as a sentry to protect outposts or early game bases.
Size: Small
Artillery Towers fires small explosives with little energy at long range, but has weak damage. This building should act as a deterrent a.k.a "all bark, no bite" turret. Basically, a turret or turrets that large armies can ignore.
Size: Medium

Anti-air can only attack air. They have large range, but are large and energy expensive.
Size: Large

Faction-Based towers are specialist towers. For example, anti-armor towers or mortar towers.

Number 2: Increase Construction Time of Production Buildings.
Production facilities are the most important building in Evolution RTS. It produces units to attack, defend, repair, and conquer, so player production should be crippled when it is destroyed. Therefore, production facilities should have their construction time increased to 30 seconds. This decreases the chance of players to make a comeback when they've clearly lost the battlefield. On the contrary, it can also cripple an unsuspecting player from winning. Both incentivizes players to harass production facilities bringing the battle to the home front.

Number 3: Increase Requirements of Units. Decrease Supply Cost for Late Game Units, but increase Energy Cost for Late Game Units.
No player should have access to all units at the 4 minute mark and is also completely unnecessary(I've done it and so can better players).
However, a player should not have to replace most of its units for specialized end game units. An energy penalty is suggested to compensate for the excessive amounts of late game energy.

If a player wants to end a siege, they should be able to do so swiftly.

**Comment by ForbodingAngel** [comment]
Crap, I thought you were reporting actual issues like bugs and stuff. My bad. I'll redirect this to your forum thread. Sorry about that, my mistake.

http://steamcommunity.com/app/291150/discussions/0/
