### ISSUE TITLE
Figuring out where my maps and games needed to be to get the lobby to work was a pain.

### ISSUE THREAD

**Issue by left1000** [EvolutionRTS/Evolution-RTS#49]
Figuring out where my maps and games needed to be to get the lobby to work was a pain.
I unzipped the download for weblobby into d:\spring\weblobby-1.5-windows\
I went into the game and I set the install location to d:\spring\ because all my old maps and games from springlobby were in d:\spring\maps or games
then I restarted the game and spent about an hour trying to get it to work.
It seemed the randomly when I restarted the client, the settings would either be saved from last time, not saved from last time, or somehow unbelievably reverted to whatever they were two restarts ago instead of one.
Something about the settings getting saved isn't right. Additionally the weblobby kept downloading the map and game successfully, only when it was checking for the map and game to actually work... it must've been checking a different directory than the one it was downloading to.

So I copied the maps and games from /maps and /games into just d:\spring
then i deleted all the settings I'd entered and restarted the client and it worked.

If a player downloads a map from weblobby after the download is finished and the lobby initializes it should find the map. It seems that somehow the program is capable of thinking the download folder for maps is different from the folder it loads maps from.
Although weirdly part way through this process I was able to load the map, but not the game. Despite having done nothing differently between them.
I think part of this has to do with various lobbies and programs in general throwing things like maps into /users/<username>/etc
Either way though this is a bug, that you can successfully download a map and game, find the files on your harddrive, yet be unable to have the game find them, and have to just guess randomly where to copy them to.

In fact it seems the only setting change that helped me at all was deleting the custom installation folder of D:\spring
as in the end deleting the files in D:\spring\ and D:\spring\maps
changed nothing, but deleting the files in C:\Users<user>\Documents\My Games\Spring
broke things. It would seem the custom setting for the installation folder just flat out doesn't work. As only deleting it and redownloading the files let me launch a game. Either remove the option or make it work? It's very confusing to have no idea where files need to be to work. Having a download go to one location while the files need to be in another.

**Comment by ForbodingAngel** [comment]
Not sure how I never saw this issue. Anyway, basically you would have grabbed the zip with only weblobby in it, as a result I can tell you that weblobby would have been placing the maps in my documents/my games/spring/maps. If you're on linux then it goes in ~/.spring/maps. These are the proper locations because those are the "common spring locations". Basically it means that the engine and lobbies always look there for content.

**Comment by left1000** [comment]
Years ago when spring was more populated and I used the tasclient I kept everything in one folder and this user stuff just wasn't done. I found that simpler. You might be right though that the current modern crop of spring client's all operate this way.

It might be a nice solution to both my confusion, and modern paradigms to simply place a folder shortcut inside my installation folder pointing to my user folder so that a person who doesn't know anything about user folders is pointed towards them.

**Comment by ForbodingAngel** [comment]
Shortcuts on windows don't work like that, unfortunately. Shortcuts require an absolute path and you can't get away with using environment variables either. As a result, in order for me to have a shortcut that linked you there, I would need to know your computer username, which simply isn't feasible. I'm on the verge of doing away with portable installs. They cause too many problems whereas the steam install just works.
