### ISSUE TITLE
Morphing units don't take damage while they morph.

### ISSUE THREAD

**Issue by IKRadulov** [EvolutionRTS/Evolution-RTS#57]
I launched a nucler missile on my units and all died exept one witch was morphin into a turret .

**Comment by ForbodingAngel** [comment]
They do indeed take full damage. The nukes have a pretty low area of effect, so it is likely that the units that were morphing into a turret were just outside the blast radius.

Tested and confirmed that morphing is working properly.

**Comment by sprunk** [comment]
This can happen when a unit finishes morphing after the nuke explodes but before the shockwave reaches it. I think the engine does not expose any interfaces to deal with it though. I'll mantis the issue and maybe submit a patch to the morph gadget if something happens in engine.

**Comment by ForbodingAngel** [comment]
I'm fine with it being fixed, but honestly, at this point the shockwaves are instant, so the possibility of it happening are very remote.

**Comment by sprunk** [comment]
It would help other games though (at this point everybody uses morph). https://springrts.com/mantis/view.php?id=5824
