### ISSUE TITLE
Custom Unit Shaders error in 103+

### ISSUE THREAD

**Issue by ForbodingAngel** [EvolutionRTS/Evolution-RTS#86]
`[f=-000001] Error: Failed to load: api_custom_unit_shaders.lua  (Include() could not load 'luarules/utilities/unitrendering.lua') Error: Failed to load: api_custom_unit_shaders.lua  (Include() could not load 'luarules/utilities/unitrendering.lua')`

**Comment by sprunk** [comment]
Does this reproduce? Looks like a download bug.

**Comment by ForbodingAngel** [comment]
I ended up removing CUS because there was no work being done to fix the issues in the main repo for it. Gajop acted interesting in fixing it, but I never heard anything about it, so I ended up removing it entirely. It should be noted that I did hack together a fix, but I am not comfortable with bandaid fixes that are incompatible with upstream. Had I known that CUS would remain broken and untouched for all this time I might have reconsidered removing it entirely.

This is the main repo:
https://github.com/jk3064/Custom-Unit-Shader-Framework

This is Gajop's fork:
https://github.com/gajop/Custom-Unit-Shader-Framework

This is where I addressed it on the spring forums:
https://springrts.com/phpbb/viewtopic.php?t=34618

Here is a pull request after cannibalizing from ZK:
https://github.com/gajop/Custom-Unit-Shader-Framework/pull/1

And here is my fork of the repo that I don't remember making but apparently contains some fixes:
https://github.com/ForbodingAngel/Custom-Unit-Shader-Framework

Sprung, since apparently neither JK nor Gajop have any intention of fixing CUS in a uniform and working way, would you be interested in abstracting CUS from ZK (because it is the most likely to have up to date fixes and we can verify at the outset that it is working properly) and putting it in the Spring Helper Projects ( https://github.com/Spring-Helper-Projects/ ) organization?

**Comment by sprunk** [comment]
I'd be interested in helping but it's going to be fairly low priority (I don't expect to have the spare time until the Christmas break).

**Comment by ForbodingAngel** [comment]
Yeah that's no worries. I gave up on CUS a long time ago. I think it would be beneficial for it to be easily implementable in projects, but for myself, while it would be nice, I'm not particularly clamoring for it. That said, I think it needs to be done just for the sake of doing it is a positive movement.
