### ISSUE TITLE
License could be more clear

### ISSUE THREAD

**Issue by ng-0** [EvolutionRTS/Evolution-RTS#94]
> All assets are CC BY SA except where otherwise marked (Most LUA falls under GPL, for example).

This leaves you as a person trying to integrate this into a GNU system as a package with more questions than answers. Most of the lua files I looked at didn't have an license header or any kind of license statement.
To avoid confusion on system level I'd suggest that you specificy the license more explicitly, for example like 0ad does, or like mediagoblin (https://git.savannah.gnu.org/cgit/mediagoblin.git/tree/COPYING).

**Comment by ForbodingAngel** [comment]
All code is lgpl v3, everything else is cc by sa

**Comment by Mailaender** [comment]
Which version of https://creativecommons.org/licenses/by-sa/?

**Comment by Mailaender** [comment]
Also code does not seem to be LGPL-3.0 but GPL-2.0 at least partly:
https://github.com/EvolutionRTS/Evolution-RTS/blob/20f39eff5dfd60035f51c099cfbc27fc0f5a446d/LuaUI/Widgets_Evo/unit_stockpile_EvoRTS.lua#L9

**Comment by Mailaender** [comment]
https://github.com/EvolutionRTS/Evolution-RTS/blob/master/Creative%20Commons%20%E2%80%94%20Attribution-ShareAlike%204.0%20International%20%E2%80%94%20CC%20BY-SA%204.pdf found it. Most people use the text version on GitHub. You can also just link it. The license permits it.
